# Uncomment this line to define a global platform for your project
# Uncomment this line if you're using Swift
use_frameworks!


target 'NKTube' do
    use_frameworks!
    pod 'Alamofire'
    pod 'XCDYouTubeKit'
    pod 'SDWebImage'
    pod 'MBProgressHUD'
    pod 'AppAuth'
    pod 'DZNEmptyDataSet'
    pod 'Firebase'
    pod 'Firebase/Core'
    pod 'Firebase/AdMob'
    
    pod 'RNCryptor'
    pod 'Flurry-iOS-SDK/FlurrySDK'
    pod 'ObjectMapper'


end

target 'NKTubeTests' do

end

target 'NKTubeUITests' do

end

