# Uncomment this line to define a global platform for your project
# Uncomment this line if you're using Swift
use_frameworks!


target 'NKTube' do
    use_frameworks!
    pod 'Alamofire'
#    pod 'XCDYouTubeKit'
    pod 'XCDYouTubeKit'
    pod 'SDWebImage'
    pod 'MBProgressHUD'
#    pod 'google-plus-ios-sdk', '~> 1.7'
#    pod 'Google'
#    pod 'Google/SignIn'
    pod 'AppAuth'
    pod 'DZNEmptyDataSet'
    pod 'Firebase'
    pod 'Firebase/Core'
    pod 'Firebase/AdMob'
    
    pod 'RNCryptor'
    pod 'Flurry-iOS-SDK/FlurrySDK'

end

target 'NKTubeTests' do

end

target 'NKTubeUITests' do

end

